# Generated by Django 5.2.17 on 2026-09-09 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(default=2026)),
                ('jornada', models.PositiveIntegerField()),
                ('puntos_app', models.IntegerField(default=0)),
                ('aciertos_quinielas', models.PositiveIntegerField(default=0)),
                ('aciertos_porras', models.PositiveIntegerField(default=0)),
                ('penalizacion_dinero_clausulas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('penalizacion_puntos_clausulas', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clausula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('jugador', models.CharField(max_length=120)),
                ('valor_dinero', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('penalizacion_dinero', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('penalizacion_puntos', models.IntegerField(default=0)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clausulas', to='core.jornadaregistro')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, max_length=80)),
                ('must_change_password', models.BooleanField(default=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jornadaregistro',
            name='user_access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.useraccess'),
        ),
        migrations.AlterUniqueTogether(
            name='jornadaregistro',
            unique_together={('user_access', 'season', 'jornada')},
        ),
    ]
