# Generated by Django 5.2.17 on 2026-09-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadaregistro',
            name='cerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jornadaregistro',
            name='datos',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
