# Generated by Django 5.2.17 on 2026-09-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_useraccess_roles_and_divisions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=80)),
                ('manager', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('provincia', models.CharField(max_length=80)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('division', 'manager')},
            },
        ),
    ]
