# Generated by Django 5.2.17 on 2026-09-16 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactomanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('equipo_local', models.CharField(max_length=80)),
                ('equipo_visitante', models.CharField(max_length=80)),
                ('fecha_cierre', models.DateTimeField()),
                ('goles_reales', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VotoPartidoVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=80)),
                ('manager', models.CharField(max_length=120)),
                ('posicionamiento', models.CharField(choices=[('local', 'Equipo local'), ('visitante', 'Equipo visitante'), ('ninguno', 'Ninguno')], max_length=12)),
                ('pronostico_goles', models.CharField(choices=[('0', '0 goles'), ('1', '1 gol'), ('2', '2 goles'), ('3+', '3 o más goles')], max_length=2)),
                ('objetivo_penalizacion', models.CharField(blank=True, max_length=120)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='core.partidovip')),
            ],
            options={
                'unique_together': {('partido', 'division', 'manager')},
            },
        ),
    ]
