# Generated by Django 5.2.17 on 2026-09-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_partidovip_votopartidovip'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidovip',
            name='escudo_local',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='partidovip',
            name='escudo_visitante',
            field=models.URLField(blank=True),
        ),
    ]
